import { describe, expect, it } from 'vitest';

import { parseSource, serialise } from './convert';
import suite from './spec/yaml-test-suite.json';

/**
 * THE YAML WRAPPER, AGAINST THE CORPUS EVERY YAML IMPLEMENTATION IS MEASURED
 * AGAINST.
 *
 * The `yaml` package is held to the yaml-test-suite upstream. What was held to
 * nothing outside this repository was the WRAPPER around it in `convert.ts` -
 * the JSON boundary, the duplicate-key rule, the alias limit, the
 * empty-document rule and the stream-to-array decision - and that wrapper is
 * where every one of this tool's own YAML answers is actually decided. It had
 * example-based tests only, and an example-based test for a format this large
 * is a test that the file agrees with the module beside it.
 *
 * The fixture is [`spec/yaml-test-suite.json`](./spec/yaml-test-suite.json),
 * generated by `scripts/generate-yaml-oracle.mjs` from the suite's own
 * `data-2022-01-17` tag and committed, so nothing here reaches the network and
 * a change to either side is a diff in review. Each case carries the document
 * and then either the value a conforming parser must produce or a marker
 * saying the document must be refused.
 *
 * WHAT THIS DOES NOT CLAIM. The suite's `in.json` is the value, not the
 * spelling: JSON objects are unordered, so one case below differs only in the
 * order the suite chose to print a mapping in. And 29 cases describe their
 * expectation as an event stream with no JSON at all; those are counted rather
 * than dropped, so the number of cases this fixture cannot decide is a number
 * somebody can see.
 *
 * THE DIVERGENCE LIST IS EXACT, NOT A THRESHOLD, and every entry is asserted
 * to STILL diverge. Fixing one is meant to turn this file red, so that the
 * behaviour and the list are changed together.
 */

interface SuiteCase {
  readonly id: string;
  readonly label: string;
  readonly yaml: string;
  readonly error: boolean;
  readonly documents?: readonly unknown[] | null;
}

const cases = suite.cases as readonly SuiteCase[];

/** The wrapper's own rule: one document is itself, a stream is an array. */
function expectedValue(documents: readonly unknown[]): unknown {
  return documents.length === 1 ? documents[0] : documents;
}

/**
 * Every case where this tool's answer is not the suite's, with the reason.
 *
 * They fall into three groups and no others, which is the useful part:
 *
 *  1. AN EMPTY DOCUMENT IS DROPPED. A document holding only a directive, a
 *     comment or a bare `---` is `null` to the suite and nothing at all to
 *     this tool - `isEmptyDocument` exists so that an empty box says "nothing
 *     to parse" rather than producing `null`, which is the right answer for
 *     the single-document case that every user is in. In a STREAM it is a
 *     silent loss: the array comes back shorter than the file. That is named
 *     in docs/conversion-matrix.md rather than fixed here, because this round
 *     pins YAML behaviour and a later one changes it.
 *
 *  2. A VALUE JSON CANNOT HOLD IS REFUSED BY PATH. `!!set` is a Set, `!!omap`
 *     a Map, `!!binary` a byte array. The suite prints a JSON rendering of
 *     each; this tool refuses and says where, which is the documented
 *     behaviour of the JSON boundary and the opposite of mangling.
 *
 *  3. ONE ORDERING. RR7F is `a` then an explicit `? d`, and the suite's
 *     `in.json` prints `d` first. JSON objects are unordered so neither is
 *     wrong; this tool preserves the document's order, which is what it
 *     promises everywhere else.
 */
const EXPECTED_DIFFERENCES: Readonly<Record<string, string>> = {
  '2XXW': 'a !!set becomes a Set, refused at the JSON boundary',
  '565N': 'a !!binary becomes a byte array, refused at the JSON boundary',
  J7PZ: 'an !!omap becomes a Map, refused at the JSON boundary',

  '6XDY': 'two document-start markers and nothing else: every document is empty',
  '8G76': 'comment lines only',
  '98YD': 'comment lines only',
  AVM7: 'an empty stream',
  'DK95/07': 'a directive and a tab, and no content',
  HWV9: 'a document-end marker and nothing else',
  'MUS6/02': 'a directive and no content',
  'MUS6/03': 'a directive and no content',
  'MUS6/04': 'a directive and no content',
  'MUS6/05': 'a directive and no content',
  'MUS6/06': 'a directive and no content',
  QT73: 'a comment and a document-end marker',

  '6ZKB': 'a stream whose second document is empty, so the array is one short',
  '9DXL': 'a stream whose second document is empty, so the array is one short',
  PUW8: 'a trailing `---` with nothing after it is dropped from the stream',
  UT92: 'a stream ending in an empty document',
  W4TN: 'a stream ending in an empty document',

  RR7F: 'the suite prints the mapping in a different order; JSON objects are unordered',
};

/** True when this tool agrees with the suite about a value case. */
function agrees(entry: SuiteCase): boolean {
  const documents = entry.documents;
  if (documents === null || documents === undefined) return false;
  const result = parseSource(entry.yaml, 'yaml', ',');
  if (!result.ok) return false;
  return JSON.stringify(result.value) === JSON.stringify(expectedValue(documents));
}

describe('the fixture itself', () => {
  /*
   * Every assertion below is satisfied by an empty fixture, so this is the one
   * that says the file was really loaded and really holds what it claims.
   */
  it('holds the suite it says it holds', () => {
    expect(suite.generator).toContain('yaml-test-suite');
    expect(suite.contentDigest).toMatch(/^sha256:[0-9a-f]{64}$/);
    expect(cases.length).toBeGreaterThan(350);
    expect(suite.counts.error).toBeGreaterThan(80);
    expect(suite.counts.withJson).toBeGreaterThan(250);
  });

  it('counts what it cannot decide, rather than dropping it', () => {
    const undecidable = cases.filter(
      (entry) => !entry.error && (entry.documents === null || entry.documents === undefined),
    );
    // Cases the suite describes only as an event stream. The number is pinned
    // so that a regeneration which quietly stopped reading `in.json` would
    // show up here rather than as a smaller corpus passing just as happily.
    expect(undecidable).toHaveLength(suite.counts.eventStreamOnly);
    expect(suite.counts.eventStreamOnly).toBe(29);
  });
});

describe('reading, against the yaml-test-suite', () => {
  const valueCases = cases.filter(
    (entry) => !entry.error && entry.documents !== null && entry.documents !== undefined,
  );

  it.each(
    valueCases
      .filter((entry) => !(entry.id in EXPECTED_DIFFERENCES))
      .map((entry) => [`${entry.id} ${entry.label}`, entry] as const),
  )('reads %s to the value the suite gives', (_name, entry) => {
    const result = parseSource(entry.yaml, 'yaml', ',');
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value).toEqual(expectedValue(entry.documents ?? []));
    }
  });

  it.each(Object.entries(EXPECTED_DIFFERENCES))(
    'still differs from the suite on %s, because %s',
    (id) => {
      const entry = cases.find((candidate) => candidate.id === id);
      expect(entry).toBeDefined();
      if (entry === undefined) return;
      // Asserted as a difference rather than filtered out. Making one of these
      // agree is a behaviour change, and it should arrive with this list
      // edited rather than silently.
      expect(agrees(entry)).toBe(false);
    },
  );

  it('agrees with the suite on the overwhelming majority of value cases', () => {
    const agreed = valueCases.filter((entry) => agrees(entry));
    // A number rather than a ratio, so a corpus that shrank could not satisfy
    // it. It moves only when behaviour or the fixture moves.
    expect(agreed).toHaveLength(valueCases.length - Object.keys(EXPECTED_DIFFERENCES).length);
    expect(agreed.length).toBeGreaterThan(250);
  });
});

describe('refusing, against the yaml-test-suite', () => {
  const errorCases = cases.filter((entry) => entry.error);

  it.each(errorCases.map((entry) => [`${entry.id} ${entry.label}`, entry] as const))(
    'refuses %s, which the suite marks as an error',
    (_name, entry) => {
      const result = parseSource(entry.yaml, 'yaml', ',');
      expect(result.ok).toBe(false);
    },
  );

  /*
   * A NEGATIVE CONTROL, BECAUSE EVERY ONE OF THOSE PASSED ON THE FIRST RUN.
   *
   * 94 documents, all refused, no exceptions - which is either a parser that
   * is right or a harness that cannot tell. These three say it can tell: a
   * document the suite would have marked an error is refused, and two
   * perfectly ordinary documents are NOT, so the assertion above is not
   * "parseSource always fails".
   */
  it('can tell a refusal from an acceptance', () => {
    expect(parseSource('a:\n- b\n  c: d\n', 'yaml', ',').ok).toBe(false);
    expect(parseSource('a: 1\n', 'yaml', ',').ok).toBe(true);
    expect(parseSource('- 1\n- 2\n', 'yaml', ',').ok).toBe(true);
  });

  /*
   * And the same for the value half: the comparison has to be able to notice a
   * wrong answer. A fixture whose expected value has been corrupted must fail,
   * or "258 of the 279 value cases agree" means nothing.
   */
  it('can tell a right answer from a wrong one', () => {
    const entry = cases.find((candidate) => candidate.id === '229Q');
    expect(entry).toBeDefined();
    if (entry === undefined) return;

    expect(agrees(entry)).toBe(true);
    const corrupted: SuiteCase = { ...entry, documents: [{ name: 'not what the suite says' }] };
    expect(agrees(corrupted)).toBe(false);
  });
});

/* ========================================================================== *
 * Writing: our YAML, read by an implementation that shares nothing with ours
 * ========================================================================== */

/**
 * OUR YAML OUTPUT, READ BY js-yaml.
 *
 * Nothing outside this repository had ever read a byte of YAML this tool
 * wrote. The reader and the writer are the same package, so `parse(stringify(
 * x))` is a round trip through one implementation - which passes just as
 * happily when both halves are wrong in mirror-image ways, and is the exact
 * thing docs/conversion-matrix.md refuses to count as evidence.
 *
 * js-yaml is a separate implementation with a separate ancestry (it is a port
 * of PyYAML). It is a devDependency and it is imported only here, so it
 * reaches no chunk the browser loads - `pnpm bundle:check` is what keeps that
 * true rather than this sentence.
 *
 * The corpus is the suite's own documents rather than values invented here:
 * every case the tool can read is re-serialised and handed to js-yaml, so what
 * is being checked is our writer over input somebody else chose.
 */
/**
 * The one document whose YAML js-yaml will not read back, and why it stays.
 *
 * NAT4 holds strings that are nothing but newlines. Our writer emits `"\n"` as
 * a keep-chomped literal block scalar with no indentation indicator:
 *
 *     e: |+
 *
 * js-yaml 5.4.2 refuses that with "bad indentation of a mapping entry",
 * because auto-detecting the block's indentation needs a non-empty line and
 * there is none.
 *
 * A DISAGREEMENT BETWEEN TWO IMPLEMENTATIONS IS NOT EVIDENCE ABOUT EITHER, so
 * a third was asked. CPython's PyYAML 6.0.3 reads the same bytes as `'\n'` -
 * the value our writer meant - both with and without an explicit indentation
 * indicator. Two of the three agree with our output, so this is recorded as
 * js-yaml's limit rather than as a defect in what this tool writes, and it is
 * named here rather than filtered out by a threshold.
 */
const WRITER_DIFFERENCES: Readonly<Record<string, string>> = {
  NAT4: 'a string of only newlines is written as `|+`, which js-yaml 5.4.2 refuses and PyYAML 6.0.3 reads correctly',
};

const writable = cases.filter((entry) => {
  if (entry.error) return false;
  if (entry.documents === null || entry.documents === undefined) return false;
  if (entry.id in WRITER_DIFFERENCES) return false;
  return parseSource(entry.yaml, 'yaml', ',').ok;
});

describe('writing, against js-yaml', () => {
  it('has a corpus to check at all', () => {
    expect(writable.length).toBeGreaterThan(250);
  });

  it.each(writable.map((entry) => [`${entry.id} ${entry.label}`, entry] as const))(
    'writes %s as YAML js-yaml reads back to the same value',
    async (_name, entry) => {
      const { load } = await import('js-yaml');

      const parsed = parseSource(entry.yaml, 'yaml', ',');
      expect(parsed.ok).toBe(true);
      if (!parsed.ok) return;

      const written = serialise(parsed.value, 'yaml', { indent: 2, delimiter: ',' });
      expect(written.ok).toBe(true);
      if (!written.ok) return;

      // `load` refuses a multi-document stream, which is right: this tool
      // never writes one (a stream becomes a sequence, which the matrix names
      // as its own loss), so a document js-yaml refuses here would be a real
      // finding rather than an API mismatch.
      const readBack: unknown = load(written.value);
      expect(readBack).toEqual(parsed.value);
    },
  );

  /*
   * THE NEGATIVE CONTROL FOR THE WRITER.
   *
   * 250-odd documents agreeing on the first run is the shape of a test that
   * is not running. These two say the comparison has teeth: a string js-yaml
   * reads as something else must fail, and a document whose YAML is subtly
   * damaged must fail.
   */
  it('can tell a faithful serialisation from a damaged one', async () => {
    const { load } = await import('js-yaml');

    // Exactly the scalars a writer that forgot to quote would lose: `1.10`
    // becomes the number 1.1, `0123` becomes 123.
    const value = { version: '1.10', id: '0123' };
    const written = serialise(value, 'yaml', { indent: 2, delimiter: ',' });
    expect(written.ok).toBe(true);
    if (!written.ok) return;

    expect(written.value).toContain('"1.10"');
    expect(load(written.value)).toEqual(value);

    // The same document with the quotes taken out does NOT come back, which is
    // what says the assertion above is reading something rather than agreeing
    // with everything.
    expect(load(written.value.replaceAll('"', ''))).not.toEqual(value);
  });

  /*
   * And the exception above is asserted as itself, so that a js-yaml release
   * which learns to read `|+` turns this file red rather than leaving a case
   * silently excluded forever.
   */
  it.each(Object.entries(WRITER_DIFFERENCES))(
    'js-yaml still cannot read our output for %s, because %s',
    async (id) => {
      const { load } = await import('js-yaml');
      const entry = cases.find((candidate) => candidate.id === id);
      expect(entry).toBeDefined();
      if (entry === undefined) return;

      const parsed = parseSource(entry.yaml, 'yaml', ',');
      expect(parsed.ok).toBe(true);
      if (!parsed.ok) return;

      const written = serialise(parsed.value, 'yaml', { indent: 2, delimiter: ',' });
      expect(written.ok).toBe(true);
      if (!written.ok) return;

      expect(() => load(written.value)).toThrow();
    },
  );
});
