import { describe, expect, it } from 'vitest';

import { parseSource, serialise } from './convert';
import suite from './spec/yaml-test-suite.json';

/**
 * THE YAML WRAPPER, AGAINST THE CORPUS EVERY YAML IMPLEMENTATION IS MEASURED
 * AGAINST.
 *
 * The `yaml` package is held to the yaml-test-suite upstream. What was held to
 * nothing outside this repository was the WRAPPER around it in `convert.ts` -
 * the value-model boundary, the duplicate-key rule, the alias limit, the
 * empty-document rule and the stream-to-array decision - and that wrapper is
 * where every one of this tool's own YAML answers is actually decided. It had
 * example-based tests only, and an example-based test for a format this large
 * is a test that the file agrees with the module beside it.
 *
 * The fixture is [`spec/yaml-test-suite.json`](./spec/yaml-test-suite.json),
 * generated by `scripts/generate-yaml-oracle.mjs` from the suite's own
 * `data-2022-01-17` tag and committed, so nothing here reaches the network and
 * a change to either side is a diff in review. Each case carries the document
 * and then either the value a conforming parser must produce or a marker
 * saying the document must be refused.
 *
 * WHAT THIS DOES NOT CLAIM. The suite's `in.json` is the value, not the
 * spelling: JSON objects are unordered, so one case below differs only in the
 * order the suite chose to print a mapping in.
 *
 * AND THE 29 THAT USED TO BE COUNTED ARE NOW DECIDED. Those are the cases the
 * suite answers only as an event stream. Round five composes the value from
 * those events in the generator - 13 of them have a JSON value this tool is
 * held to, and the other 16 have a reason it does not, which is itself an
 * expectation: a refusal this tool documents, asserted by name. See "the cases
 * the suite answers only as events" below.
 *
 * THE DIVERGENCE LIST IS EXACT, NOT A THRESHOLD, and every entry is asserted
 * to STILL diverge. Fixing one is meant to turn this file red, so that the
 * behaviour and the list are changed together.
 */

interface SuiteCase {
  readonly id: string;
  readonly label: string;
  readonly yaml: string;
  readonly error: boolean;
  readonly documents?: readonly unknown[] | null;
  /** True for a case whose expectation was composed from its `test.event`. */
  readonly fromEvents?: boolean;
  /** Why that composed value has no JSON form, for the ones that do not. */
  readonly reason?: string;
}

const cases = suite.cases as readonly SuiteCase[];

/** The wrapper's own rule: one document is itself, a stream is an array. */
function expectedValue(documents: readonly unknown[]): unknown {
  return documents.length === 1 ? documents[0] : documents;
}

/**
 * Every case where this tool's answer is not the suite's, with the reason.
 *
 * TWENTY-ONE OF THESE BECAME NINE. Twelve of them were one rule, and the rule
 * was wrong: an empty document was dropped whether or not a `---` had declared
 * it. `---` starts a document and an empty one is `null`, which the suite says,
 * js-yaml 5.4.2 says, and CPython's PyYAML 6.0.3 says about the very same
 * bytes - so a five-document stream came back as a four-element array with no
 * error. See `isEmptyDocument`. The list below is what is LEFT, and the three
 * groups it falls into are each a decision rather than a defect:
 *
 *  1. A VALUE JSON CANNOT HOLD IS REFUSED BY PATH. `!!set` is a Set, `!!omap`
 *     a Map, `!!binary` a byte array. The suite prints a JSON rendering of
 *     each; this tool refuses and says where, which is the documented
 *     behaviour of the value-model boundary and the opposite of mangling. Justified:
 *     the alternative is inventing a JSON spelling for a YAML type and handing
 *     it back as though nothing happened.
 *
 *  2. A STREAM OF NO DOCUMENTS AT ALL. Nothing, comments only, or a lone `...`:
 *     the suite's expectation is an empty list of documents, and this tool says
 *     "nothing to parse: the input is empty". Those agree about the FACT and
 *     differ about how to present it, and an empty input box is the one place
 *     where a sentence beats a value. Justified, and note that PyYAML refuses
 *     two of these five outright, so the suite's `[]` is not the only answer a
 *     conforming implementation gives.
 *
 *  3. ONE ORDERING. RR7F is `a` then an explicit `? d`, and the suite's
 *     `in.json` prints `d` first. JSON objects are unordered so neither is
 *     wrong; this tool preserves the document's order, which is what it
 *     promises everywhere else. Justified.
 */
const EXPECTED_DIFFERENCES: Readonly<Record<string, string>> = {
  '2XXW': 'a !!set becomes a Set, refused at the value-model boundary',
  '565N': 'a !!binary becomes a byte array, refused at the value-model boundary',
  J7PZ: 'an !!omap becomes a Map, refused at the value-model boundary',

  '8G76': 'comment lines only, so the stream holds no documents',
  '98YD': 'comment lines only, so the stream holds no documents',
  AVM7: 'an empty stream',
  HWV9: 'a document-end marker and nothing else',
  QT73: 'a comment and a document-end marker',

  RR7F: 'the suite prints the mapping in a different order; JSON objects are unordered',
};

/**
 * The twelve that used to be here, asserted as AGREEING now.
 *
 * A list that shrinks is a list somebody could have shrunk by deleting from it.
 * These are the ids the empty-document fix was for, and each one is checked to
 * produce the suite's own value - so the fix cannot be quietly reverted, and
 * the divergence list above cannot be quietly edited, without this failing.
 */
const FIXED_THIS_ROUND: readonly string[] = [
  '6XDY',
  'DK95/07',
  'MUS6/02',
  'MUS6/03',
  'MUS6/04',
  'MUS6/05',
  'MUS6/06',
  '6ZKB',
  '9DXL',
  'PUW8',
  'UT92',
  'W4TN',
];

/** True when this tool agrees with the suite about a value case. */
function agrees(entry: SuiteCase): boolean {
  const documents = entry.documents;
  if (documents === null || documents === undefined) return false;
  const result = parseSource(entry.yaml, 'yaml', ',');
  if (!result.ok) return false;
  return JSON.stringify(result.value) === JSON.stringify(expectedValue(documents));
}

describe('the fixture itself', () => {
  /*
   * Every assertion below is satisfied by an empty fixture, so this is the one
   * that says the file was really loaded and really holds what it claims.
   */
  it('holds the suite it says it holds', () => {
    expect(suite.generator).toContain('yaml-test-suite');
    expect(suite.contentDigest).toMatch(/^sha256:[0-9a-f]{64}$/);
    expect(cases.length).toBeGreaterThan(350);
    expect(suite.counts.error).toBeGreaterThan(80);
    expect(suite.counts.withJson).toBeGreaterThan(250);
  });

  /*
   * THE 29 THE FIXTURE USED TO BE UNABLE TO DECIDE.
   *
   * They carry no `in.json`, and for three rounds this file counted them and
   * moved on - visible, which was the point, and undecided, which was the cost.
   * They carry a `test.event` like every other case, and an event stream is a
   * complete description of the node graph: what opened, what closed, every
   * scalar with the style it was written in, every anchor and every alias. So
   * the generator composes the value from it.
   *
   * AND THE COMPOSER IS NOT TRUSTED ON ITS OWN SAY-SO. It is code this
   * repository wrote, which is the evidence this document ranks lowest. Before
   * it is allowed to decide a case the suite does not answer, it has to
   * reproduce the ones the suite DOES: 278 of the 279, with the one exception
   * being RR7F, whose `in.json` prints a mapping in a different order and which
   * this file has called an ordering difference since round two. The generator
   * throws rather than writing a fixture if any other case disagrees.
   */
  it('decides every case, including the ones the suite answers only as events', () => {
    const fromEvents = cases.filter((entry) => entry.fromEvents === true);
    expect(fromEvents).toHaveLength(29);
    expect(suite.counts.fromEvents).toBe(29);

    // The composer's credentials, in the fixture rather than in a comment.
    expect(suite.counts.composerAgreedWithJson).toBe(278);

    // 13 have a JSON value; the other 16 have a reason, and every one of those
    // reasons is a refusal this tool already documents.
    expect(suite.counts.fromEventsWithValue).toBe(13);
    expect(Object.keys(suite.counts.fromEventsByReason).sort()).toEqual([
      'collection-key',
      'duplicate-key',
    ]);
    expect(suite.counts.fromEventsByReason['collection-key']).toHaveLength(15);
    expect(suite.counts.fromEventsByReason['duplicate-key']).toEqual(['2JQS']);

    // Nothing is left over: 29 = 13 + 15 + 1.
    const undecided = fromEvents.filter(
      (entry) => entry.documents === null || entry.documents === undefined,
    );
    expect(undecided).toHaveLength(16);
    expect(undecided.every((entry) => entry.reason !== undefined)).toBe(true);
  });
});

/**
 * The cases the suite answers only as an event stream, held to that answer.
 *
 * A composed VALUE is compared like any other case, up in the block above -
 * they are ordinary `documents` now. What is here is the other sixteen, where
 * the events describe something JSON has no form for. "No JSON form" is not an
 * excuse to assert nothing: this tool has a documented refusal for each of the
 * two reasons, and being refused for the RIGHT one is the assertion.
 */
describe('the cases the suite answers only as events', () => {
  const byReason = (reason: string): readonly SuiteCase[] =>
    cases.filter((entry) => entry.reason === reason);

  it.each(byReason('collection-key').map((entry) => [entry.id, entry] as const))(
    'refuses %s for the key being a collection, which is what its events say it is',
    (_id, entry) => {
      const result = parseSource(entry.yaml, 'yaml', ',');
      expect(result.ok).toBe(false);
      if (result.ok) return;
      expect(result.error.message).toBe(
        "A YAML key is itself a collection, which this tool's value model cannot hold.",
      );
    },
  );

  it.each(byReason('duplicate-key').map((entry) => [entry.id, entry] as const))(
    'refuses %s for two keys colliding, which is what its events say happens',
    (_id, entry) => {
      const result = parseSource(entry.yaml, 'yaml', ',');
      expect(result.ok).toBe(false);
      if (result.ok) return;
      // 2JQS is `: a` over `: b` - two empty keys, which are the same key. The
      // suite composes it rather than marking it an error, so the refusal is
      // this tool's and the message has to say so rather than blaming the YAML.
      expect(result.error.message).toBe('That mapping has the same key twice.');
    },
  );

  /*
   * AND THE NEGATIVE CONTROL FOR THE WHOLE BLOCK.
   *
   * Sixteen refusals could equally be one parser that refuses everything
   * awkward. These are the documents next door to them: a collection key that
   * is a VALUE rather than a key, and a mapping whose two empty-looking keys
   * are genuinely different. Both must be accepted.
   */
  it('can tell these apart from the documents beside them', () => {
    expect(parseSource('a: [1, 2]\nb: {c: d}\n', 'yaml', ',').ok).toBe(true);
    expect(parseSource('? a\n: 1\n? b\n: 2\n', 'yaml', ',').ok).toBe(true);
  });
});

/**
 * THE MESSAGE A COLLIDING KEY GETS, WHICH USED TO BE THE WRONG ONE.
 *
 * `true:` beside `"true":` is valid YAML - the suite composes documents of that
 * shape, js-yaml reads them and PyYAML reads them. What cannot hold it is the
 * value model every conversion in this tool goes through, whose keys are text,
 * so both of those become `"true"`. This tool refuses it, correctly, and until
 * round five told the person that their YAML was invalid: a sentence that sends
 * somebody looking for a syntax error that is not there.
 *
 * ROUND ELEVEN CHANGED THE WORDING AND NOT THE RULE. The message said `the same
 * JSON key`, which names a format that is in neither half of a YAML to YAML
 * run. What it was always about is the model, and it says so now.
 *
 * The two cases are separated, and the separation is asserted in both
 * directions - a genuinely duplicated key must NOT get the value-model wording
 * either, or the distinction is decoration.
 */
describe('a key that collides only once the document is read', () => {
  const refusal = (source: string): { message: string; detail: string } => {
    const result = parseSource(source, 'yaml', ',');
    expect(result.ok).toBe(false);
    return result.ok
      ? { message: '', detail: '' }
      : { message: result.error.message, detail: result.error.detail ?? '' };
  };

  const message = (source: string): string => refusal(source).message;

  it.each([
    ['a boolean against its own spelling', 'true: a\n"true": b\n'],
    ['a number against its own spelling', '1: a\n"1": b\n'],
    ['null against the empty string', '~: a\n"": b\n'],
  ])('says that %s is two YAML keys and one key here', (_name, source) => {
    expect(message(source)).toBe('Two different YAML keys become one key in this tool.');
  });

  it.each([
    ['the same plain key twice', 'a: 1\na: 2\n'],
    ['the same empty key twice', ': a\n: b\n'],
    ['the same quoted key twice', '"a": 1\n"a": 2\n'],
  ])('says that %s is the same key twice', (_name, source) => {
    expect(message(source)).toBe('That mapping has the same key twice.');
  });

  /*
   * AND THE SENTENCE UNDER THE HEADLINE IS THE ACTIONABLE HALF.
   *
   * The headline says which of the two happened; the detail says what to do
   * about it, and it is the only place the user is told that `true:` and
   * `"true":` are the two keys in question. Asserted because round five's
   * mutation sweep could turn the `+` joining those strings into a `-` - which
   * makes the whole detail the three letters `NaN` - with every other
   * assertion in this file still green.
   */
  it('says what to do about it, in both cases', () => {
    expect(refusal('true: a\n"true": b\n').detail).toContain('`true:` and `"true":` are two keys');
    expect(refusal('a: 1\na: 2\n').detail).toContain('A mapping may name each key once');
  });

  /*
   * The collision is reported at the SECOND key, and the position is what
   * makes either message actionable. Asserted because the offset the library
   * hands back is the one this file keys its side channel on: if that ever
   * stopped being the second key's start, every collision would fall through
   * to "That is not valid YAML." and every test above would still pass except
   * this one.
   */
  it('points at the second key rather than at the document', () => {
    const result = parseSource('first: 1\ntrue: a\n"true": b\n', 'yaml', ',');
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.position?.line).toBe(3);
    expect(result.error.position?.column).toBe(1);
  });
});

describe('reading, against the yaml-test-suite', () => {
  const valueCases = cases.filter(
    (entry) => !entry.error && entry.documents !== null && entry.documents !== undefined,
  );

  it.each(
    valueCases
      .filter((entry) => !(entry.id in EXPECTED_DIFFERENCES))
      .map((entry) => [`${entry.id} ${entry.label}`, entry] as const),
  )('reads %s to the value the suite gives', (_name, entry) => {
    const result = parseSource(entry.yaml, 'yaml', ',');
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value).toEqual(expectedValue(entry.documents ?? []));
    }
  });

  it.each(Object.entries(EXPECTED_DIFFERENCES))(
    'still differs from the suite on %s, because %s',
    (id) => {
      const entry = cases.find((candidate) => candidate.id === id);
      expect(entry).toBeDefined();
      if (entry === undefined) return;
      // Asserted as a difference rather than filtered out. Making one of these
      // agree is a behaviour change, and it should arrive with this list
      // edited rather than silently.
      expect(agrees(entry)).toBe(false);
    },
  );

  it.each(FIXED_THIS_ROUND)(
    'now agrees with the suite on %s, which the empty-document rule used to get wrong',
    (id) => {
      const entry = cases.find((candidate) => candidate.id === id);
      expect(entry).toBeDefined();
      if (entry === undefined) return;
      expect(agrees(entry)).toBe(true);
    },
  );

  /*
   * THE NEGATIVE CONTROL FOR THE FIX ITSELF.
   *
   * Every case above passes if `isEmptyDocument` simply stopped dropping
   * anything - and that would be a different bug, because an empty input box
   * would come back as `null` instead of saying there is nothing to parse.
   * These two are the other side of the rule, and they are what says the fix
   * was a distinction rather than a removal.
   */
  it('still drops a document with nothing in it and no marker to declare it', () => {
    expect(parseSource('', 'yaml', ',').ok).toBe(false);
    expect(parseSource('# just a comment\n', 'yaml', ',').ok).toBe(false);
  });

  it('agrees with the suite on the overwhelming majority of value cases', () => {
    const agreed = valueCases.filter((entry) => agrees(entry));
    // A number rather than a ratio, so a corpus that shrank could not satisfy
    // it. It moves only when behaviour or the fixture moves.
    expect(agreed).toHaveLength(valueCases.length - Object.keys(EXPECTED_DIFFERENCES).length);
    expect(agreed.length).toBeGreaterThan(250);
  });
});

describe('refusing, against the yaml-test-suite', () => {
  const errorCases = cases.filter((entry) => entry.error);

  it.each(errorCases.map((entry) => [`${entry.id} ${entry.label}`, entry] as const))(
    'refuses %s, which the suite marks as an error',
    (_name, entry) => {
      const result = parseSource(entry.yaml, 'yaml', ',');
      expect(result.ok).toBe(false);
    },
  );

  /*
   * A NEGATIVE CONTROL, BECAUSE EVERY ONE OF THOSE PASSED ON THE FIRST RUN.
   *
   * 94 documents, all refused, no exceptions - which is either a parser that
   * is right or a harness that cannot tell. These three say it can tell: a
   * document the suite would have marked an error is refused, and two
   * perfectly ordinary documents are NOT, so the assertion above is not
   * "parseSource always fails".
   */
  it('can tell a refusal from an acceptance', () => {
    expect(parseSource('a:\n- b\n  c: d\n', 'yaml', ',').ok).toBe(false);
    expect(parseSource('a: 1\n', 'yaml', ',').ok).toBe(true);
    expect(parseSource('- 1\n- 2\n', 'yaml', ',').ok).toBe(true);
  });

  /*
   * And the same for the value half: the comparison has to be able to notice a
   * wrong answer. A fixture whose expected value has been corrupted must fail,
   * or "258 of the 279 value cases agree" means nothing.
   */
  it('can tell a right answer from a wrong one', () => {
    const entry = cases.find((candidate) => candidate.id === '229Q');
    expect(entry).toBeDefined();
    if (entry === undefined) return;

    expect(agrees(entry)).toBe(true);
    const corrupted: SuiteCase = { ...entry, documents: [{ name: 'not what the suite says' }] };
    expect(agrees(corrupted)).toBe(false);
  });

  /* ------------------------------------------------------------------------ *
   * ...AND WHAT EACH ONE WAS REFUSED FOR
   * ------------------------------------------------------------------------ */

  /*
   * THE ASSERTION ABOVE IS `ok === false`, NINETY-FOUR TIMES, AND THAT IS ALL
   * IT IS.
   *
   * Round three found SF5V being refused by the rule that an empty input is
   * not a document - true of its bytes, and nothing to do with its fault,
   * which is two `%YAML` directives. The case had been green the whole time
   * and went on being green while the reason was wrong; what exposed it was
   * correcting the empty rule, at which point the parser started ACCEPTING a
   * document the spec calls invalid. The conclusion written down at the time
   * was that a test which passes for the wrong reason is invisible until the
   * right reason changes.
   *
   * The conclusion that was not drawn is that the other ninety-three
   * assertions have exactly the same shape. So this bucket the refusals by the
   * rule that produced them and asserts the counts - which is what would have
   * shown SF5V without anybody having to change anything, and which found 9MMA
   * in the same state on its first run: a bare `%YAML 1.2` with no document,
   * refused for being empty.
   *
   * `empty`, `depth` and `value-model` are asserted at ZERO because each is a
   * rule this file enforces on top of the parser, and a rule that also refuses
   * VALID documents of the same shape cannot be evidence that an invalid one
   * was understood.
   */
  const reasonOf = (message: string): string => {
    if (message.includes('Nothing to parse')) return 'empty';
    if (/%YAML directives|directive has no document/.test(message)) return 'directive';
    if (message.includes('nested more than')) return 'depth';
    if (message === 'That mapping has the same key twice.') return 'duplicate-key';
    if (/value model|itself a collection|become one key in this tool/.test(message))
      return 'value-model';
    return 'parser';
  };

  it('refuses each error case for a reason about the document, not about the input', () => {
    const counts = new Map<string, string[]>();

    for (const entry of errorCases) {
      const result = parseSource(entry.yaml, 'yaml', ',');
      const reason = result.ok ? 'ACCEPTED' : reasonOf(result.error.message);
      counts.set(reason, [...(counts.get(reason) ?? []), entry.id]);
    }

    // Numbers rather than "none of them", so a corpus that shrank cannot
    // satisfy this by having nothing left to classify.
    expect(errorCases).toHaveLength(94);
    expect(counts.get('ACCEPTED')).toBeUndefined();
    expect(counts.get('empty')).toBeUndefined();
    expect(counts.get('depth')).toBeUndefined();
    expect(counts.get('value-model')).toBeUndefined();
    /*
     * AND THE KEY-COLLISION RULE IS AT ZERO TOO, WHICH IT COULD NOT BE ASKED
     * BEFORE. Until round five both kinds of collision came back as "That is
     * not valid YAML.", so a case refused for having two keys the model cannot
     * tell apart was indistinguishable here from one refused for a real syntax
     * fault - and 93 of the 94 fell in the same bucket whatever their reason.
     * `Two different YAML keys become one key in this tool.` now classifies as
     * `value-model`, which is already asserted absent above.
     */
    expect(counts.get('duplicate-key')).toBeUndefined();
    expect(counts.get('directive')).toEqual(['9MMA', 'SF5V']);
    expect(counts.get('parser')).toHaveLength(92);
  });

  it('names the fault in each of the two this file refuses itself', () => {
    // The two the `yaml` package does not flag at any log level, so they are
    // the only ones whose message is ours to get right.
    const sf5v = parseSource('%YAML 1.2\n%YAML 1.2\n---\n', 'yaml', ',');
    expect(sf5v.ok).toBe(false);
    if (!sf5v.ok) expect(sf5v.error.message).toBe('That document has two %YAML directives.');

    const mma = parseSource('%YAML 1.2\n', 'yaml', ',');
    expect(mma.ok).toBe(false);
    if (!mma.ok) expect(mma.error.message).toBe('That directive has no document after it.');
  });

  it('still says "empty" about a document that really is empty', () => {
    /*
     * THE CONTROL FOR THE ZEROES ABOVE. "No error case is refused for being
     * empty" is worth nothing unless something still is - otherwise the rule
     * could have been deleted and every assertion would be greener than ever.
     */
    for (const text of ['', '   \n\n', '# only a comment\n']) {
      const result = parseSource(text, 'yaml', ',');
      expect(result.ok).toBe(false);
      if (!result.ok) expect(reasonOf(result.error.message)).toBe('empty');
    }

    // And a directive with a real document after it is not refused at all,
    // which is what keeps the new rule from being "refuse anything with a %".
    expect(parseSource('%YAML 1.2\n---\na: 1\n', 'yaml', ',').ok).toBe(true);
  });

  it('does not mistake a %YAML line inside a scalar for a directive', () => {
    /*
     * THE SUITE CAUGHT THE FIRST VERSION OF THE RULE ABOVE, ON ITS FIRST RUN.
     * XLQ9 is a multi-line scalar one of whose lines reads `%YAML 1.2`, and a
     * text scan for "a directive no --- follows" refused it - a valid document,
     * rejected by a checker written to make a refusal more precise. The rule
     * asks the parser instead: a directive with no document yields no
     * documents, and a scalar yields one.
     */
    const scalar = parseSource('--- |\n %YAML 1.2\n text\n', 'yaml', ',');
    expect(scalar.ok).toBe(true);
    if (scalar.ok) expect(scalar.value).toBe('%YAML 1.2\ntext\n');
  });
});

/* ========================================================================== *
 * Writing: our YAML, read by an implementation that shares nothing with ours
 * ========================================================================== */

/**
 * OUR YAML OUTPUT, READ BY js-yaml.
 *
 * Nothing outside this repository had ever read a byte of YAML this tool
 * wrote. The reader and the writer are the same package, so `parse(stringify(
 * x))` is a round trip through one implementation - which passes just as
 * happily when both halves are wrong in mirror-image ways, and is the exact
 * thing docs/conversion-matrix.md refuses to count as evidence.
 *
 * js-yaml is a separate implementation with a separate ancestry (it is a port
 * of PyYAML). It is a devDependency and it is imported only here, so it
 * reaches no chunk the browser loads - `pnpm bundle:check` is what keeps that
 * true rather than this sentence.
 *
 * The corpus is the suite's own documents rather than values invented here:
 * every case the tool can read is re-serialised and handed to js-yaml, so what
 * is being checked is our writer over input somebody else chose.
 */
/**
 * The one document whose YAML js-yaml will not read back, and why it stays.
 *
 * NAT4 holds strings that are nothing but newlines. Our writer emits `"\n"` as
 * a keep-chomped literal block scalar with no indentation indicator:
 *
 *     e: |+
 *
 * js-yaml 5.4.2 refuses that with "bad indentation of a mapping entry",
 * because auto-detecting the block's indentation needs a non-empty line and
 * there is none.
 *
 * A DISAGREEMENT BETWEEN TWO IMPLEMENTATIONS IS NOT EVIDENCE ABOUT EITHER, so
 * a third was asked. CPython's PyYAML 6.0.3 reads the same bytes as `'\n'` -
 * the value our writer meant - both with and without an explicit indentation
 * indicator. Two of the three agree with our output, so this is recorded as
 * js-yaml's limit rather than as a defect in what this tool writes, and it is
 * named here rather than filtered out by a threshold.
 */
const WRITER_DIFFERENCES: Readonly<Record<string, string>> = {
  NAT4: 'a string of only newlines is written as `|+`, which js-yaml 5.4.2 refuses and PyYAML 6.0.3 reads correctly',
};

const writable = cases.filter((entry) => {
  if (entry.error) return false;
  if (entry.documents === null || entry.documents === undefined) return false;
  if (entry.id in WRITER_DIFFERENCES) return false;
  return parseSource(entry.yaml, 'yaml', ',').ok;
});

describe('writing, against js-yaml', () => {
  it('has a corpus to check at all', () => {
    expect(writable.length).toBeGreaterThan(250);
  });

  it.each(writable.map((entry) => [`${entry.id} ${entry.label}`, entry] as const))(
    'writes %s as YAML js-yaml reads back to the same value',
    async (_name, entry) => {
      const { load } = await import('js-yaml');

      const parsed = parseSource(entry.yaml, 'yaml', ',');
      expect(parsed.ok).toBe(true);
      if (!parsed.ok) return;

      const written = serialise(parsed.value, 'yaml', { indent: 2, delimiter: ',' });
      expect(written.ok).toBe(true);
      if (!written.ok) return;

      // `load` refuses a multi-document stream, which is right: this tool
      // never writes one (a stream becomes a sequence, which the matrix names
      // as its own loss), so a document js-yaml refuses here would be a real
      // finding rather than an API mismatch.
      const readBack: unknown = load(written.value);
      expect(readBack).toEqual(parsed.value);
    },
  );

  /*
   * THE NEGATIVE CONTROL FOR THE WRITER.
   *
   * 250-odd documents agreeing on the first run is the shape of a test that
   * is not running. These two say the comparison has teeth: a string js-yaml
   * reads as something else must fail, and a document whose YAML is subtly
   * damaged must fail.
   */
  it('can tell a faithful serialisation from a damaged one', async () => {
    const { load } = await import('js-yaml');

    // Exactly the scalars a writer that forgot to quote would lose: `1.10`
    // becomes the number 1.1, `0123` becomes 123.
    const value = { version: '1.10', id: '0123' };
    const written = serialise(value, 'yaml', { indent: 2, delimiter: ',' });
    expect(written.ok).toBe(true);
    if (!written.ok) return;

    expect(written.value).toContain('"1.10"');
    expect(load(written.value)).toEqual(value);

    // The same document with the quotes taken out does NOT come back, which is
    // what says the assertion above is reading something rather than agreeing
    // with everything.
    expect(load(written.value.replaceAll('"', ''))).not.toEqual(value);
  });

  /*
   * And the exception above is asserted as itself, so that a js-yaml release
   * which learns to read `|+` turns this file red rather than leaving a case
   * silently excluded forever.
   */
  it.each(Object.entries(WRITER_DIFFERENCES))(
    'js-yaml still cannot read our output for %s, because %s',
    async (id) => {
      const { load } = await import('js-yaml');
      const entry = cases.find((candidate) => candidate.id === id);
      expect(entry).toBeDefined();
      if (entry === undefined) return;

      const parsed = parseSource(entry.yaml, 'yaml', ',');
      expect(parsed.ok).toBe(true);
      if (!parsed.ok) return;

      const written = serialise(parsed.value, 'yaml', { indent: 2, delimiter: ',' });
      expect(written.ok).toBe(true);
      if (!written.ok) return;

      expect(() => load(written.value)).toThrow();
    },
  );
});
