import { describe, expect, it } from 'vitest';

import { computeDiff, toUnified } from './compute';
import oracle from './spec/git-unified.json';

/**
 * THE UNIFIED PATCH, AGAINST `git diff` ITSELF.
 *
 * `toUnified` writes the format `git apply` reads, and until now every
 * expected value for it was written here by hand - which is a test that this
 * file agrees with the module next to it. The fixture in
 * [`spec/git-unified.json`](./spec/git-unified.json) is the hunks real
 * `git diff --no-index` produced for nineteen pairs of files at two context
 * widths, generated by `scripts/generate-diff-oracle.py` and committed, so the
 * suite needs no git and a change to either side is a diff in review.
 *
 * TWO QUESTIONS, ASKED SEPARATELY, because they have different answers.
 *
 *   1. IS IT SPELLED THE SAME? For 32 of the 38 it is, character for
 *      character. That number was 14 before this file existed: the hunk header
 *      was written `@@ -2,1 +2,1 @@` where every reference implementation
 *      writes `@@ -2 +2 @@`. Four of the six that remain differ only in the
 *      order of the lines inside one hunk; the other two are the line-ending
 *      disagreement below, which is not a spelling difference at all.
 *   2. DOES IT MEAN THE SAME? For all 38 it does, which is the question that
 *      actually matters and the one a spelling comparison cannot ask. The four
 *      that are spelled differently are the ones where a file's final newline
 *      changed: git groups the removals and then the additions, this groups
 *      each line with its replacement. Both are legal - a hunk's `-` lines in
 *      order are the pre-image and its `+` lines in order are the post-image,
 *      whatever order they are interleaved in - and real `git apply` was given
 *      both of this tool's versions and produced the right bytes for each.
 *
 * `applyUnified` below is what asks the second question. It is deliberately
 * not built on anything in `compute.ts`: it reconstructs the file from the
 * patch the way `patch` does, one line at a time. It is trusted because it is
 * run over GIT'S OWN hunks for all 38 cases first - if it were wrong, that is
 * where it would fail.
 */

interface Case {
  readonly name: string;
  readonly original: string;
  readonly changed: string;
  readonly context: number;
  readonly hunks: string;
}

const cases = oracle.cases as readonly Case[];

/**
 * Applies a unified patch's hunks to a file, and returns null if it does not
 * fit - a context or removal line that does not match what is there.
 *
 * Line-based, and works on the file as a list of terminated lines, because
 * `\ No newline at end of file` is a statement about the line BEFORE it.
 */
function applyUnified(original: string, hunks: string): string | null {
  if (hunks === '') return original;

  // Split keeping the terminators, so a final line without one is its own
  // entry and can be told apart from one with.
  const source = original === '' ? [] : (original.match(/[^\n]*\n|[^\n]+/g) ?? []);
  const out: string[] = [];
  let cursor = 0;

  const lines = hunks.split('\n');
  // The trailing empty string after the last terminator.
  if (lines[lines.length - 1] === '') lines.pop();

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index] ?? '';

    const header = /^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@/.exec(line);
    if (header) {
      const start = Number(header[1]);
      const count = header[2] === undefined ? 1 : Number(header[2]);
      // A hunk that starts at 0 is an insertion into an empty file.
      const from = count === 0 ? start : start - 1;
      while (cursor < from) {
        out.push(source[cursor] ?? '');
        cursor += 1;
      }
      continue;
    }

    const marker = line.charAt(0);
    const text = line.slice(1);
    // Does the NEXT line say this one had no terminator?
    const bare = lines[index + 1]?.startsWith('\\') === true;
    const terminated = bare ? text : `${text}\n`;

    if (marker === '\\') continue;

    if (marker === ' ') {
      if ((source[cursor] ?? '') !== terminated) return null;
      out.push(terminated);
      cursor += 1;
      continue;
    }

    if (marker === '-') {
      if ((source[cursor] ?? '') !== terminated) return null;
      cursor += 1;
      continue;
    }

    if (marker === '+') {
      out.push(terminated);
      continue;
    }

    return null;
  }

  while (cursor < source.length) {
    out.push(source[cursor] ?? '');
    cursor += 1;
  }

  return out.join('');
}

function ourHunks(entry: Case): string {
  const report = computeDiff(entry.original, entry.changed, {
    whitespace: 'none',
    ignoreCase: false,
    refineWords: false,
    context: entry.context,
  });
  if (!report.ok) throw new Error(report.error.message);
  return toUnified(report.value, entry.context).replace(/^--- original\n\+\+\+ changed\n/, '');
}

/**
 * The four cases whose spelling differs from git's, named rather than
 * detected. A fifth appearing is a failure, not a quietly widened exception.
 */
const SPELLED_DIFFERENTLY = ['loses its final newline', 'gains a final newline'];

/**
 * The case where this tool and git DISAGREE rather than differ in spelling.
 *
 * This tool normalises CRLF, CR and LF to one terminator before comparing, so
 * two files that differ only in their line endings come out equal and the
 * unified patch is EMPTY. Git shows every line as changed. Neither is a bug in
 * the other: git's own `--ignore-cr-at-eol` exists because the noise is often
 * not what a reader wants, and this tool takes that as its default.
 *
 * What is worth knowing is where the difference goes. It is on the report -
 * `notes.lineEndings` names both sides, and the view prints it - and it is NOT
 * on the patch, which has no way to say it. So a person reading the tool page
 * is told; a node wired from the `output` port receives an empty string. That
 * is written up in `docs/conversion-matrix.md` as a decision to take rather
 * than as a thing this test is happy about.
 */
const NORMALISES_LINE_ENDINGS = ['crlf against lf'];

describe('the patch applier this file uses as its instrument', () => {
  it('has a corpus to check at all', () => {
    expect(cases.length).toBe(38);
    expect(oracle.generator).toContain('git version');
  });

  it.each(cases.map((entry) => [`${entry.name} at -U${entry.context.toString()}`, entry] as const))(
    "reproduces the changed file from git's own patch: %s",
    (_name, entry) => {
      expect(applyUnified(entry.original, entry.hunks)).toBe(entry.changed);
    },
  );

  it('returns null for a patch that does not fit', () => {
    // The instrument has to be able to say no, or every assertion above is
    // satisfied by an applier that ignores the patch and returns its input.
    expect(applyUnified('a\nb\n', '@@ -1,2 +1,2 @@\n-q\n+Q\n b\n')).toBeNull();
  });
});

const comparable = cases.filter((entry) => !NORMALISES_LINE_ENDINGS.includes(entry.name));

describe('this tool against git diff', () => {
  it.each(
    comparable
      .filter((entry) => !SPELLED_DIFFERENTLY.includes(entry.name))
      .map((entry) => [`${entry.name} at -U${entry.context.toString()}`, entry] as const),
  )('writes the same hunks git writes: %s', (_name, entry) => {
    expect(ourHunks(entry)).toBe(entry.hunks);
  });

  it.each(
    comparable.map((entry) => [`${entry.name} at -U${entry.context.toString()}`, entry] as const),
  )('writes a patch that reproduces the changed file: %s', (_name, entry) => {
    expect(applyUnified(entry.original, ourHunks(entry))).toBe(entry.changed);
  });

  it.each(
    cases
      .filter((entry) => NORMALISES_LINE_ENDINGS.includes(entry.name))
      .map((entry) => [`${entry.name} at -U${entry.context.toString()}`, entry] as const),
  )('writes no patch where git rewrites every line: %s', (_name, entry) => {
    // The disagreement, asserted as itself. git has something to say here...
    expect(entry.hunks).toContain('@@');

    // ...and this tool has nothing to put in a patch, because it compared the
    // two files with their terminators normalised.
    expect(ourHunks(entry)).toBe('');

    // The difference is not lost, it is on the other port. A negative
    // assertion above needs this positive one beside it.
    const report = computeDiff(entry.original, entry.changed, {
      whitespace: 'none',
      ignoreCase: false,
      refineWords: false,
      context: entry.context,
    });
    expect(report.ok).toBe(true);
    if (!report.ok) return;
    expect(report.value.identical).toBe(false);
    expect(report.value.notes.lineEndings).toEqual({ original: 'crlf', changed: 'lf' });
  });

  it.each(
    cases
      .filter((entry) => SPELLED_DIFFERENTLY.includes(entry.name))
      .map((entry) => [`${entry.name} at -U${entry.context.toString()}`, entry] as const),
  )('differs from git only in the order of the lines inside the hunk: %s', (_name, entry) => {
    const ours = ourHunks(entry);

    expect(ours).not.toBe(entry.hunks);
    // Same header, same set of lines, different order - which is the whole
    // claim being made about these four.
    expect(ours.split('\n').sort()).toEqual(entry.hunks.split('\n').sort());
  });
});
