import { describe, expect, it } from 'vitest';

import { isJsonArray, isJsonObject, type ToolRunContext } from '@/features/registry/types';
import { SANITISE_SCHEMA } from '@/lib/markup/sanitise';

import textConvertTool from './index';
import corpusFile from './spec/pasted-html.corpus.json';
import oracleFile from './spec/pasted-html.oracle.json';

/**
 * EVERY CENSUS NOTE, HELD TO WHAT THREE ENGINES DREW.
 *
 * The census notes on text-convert were swept for nine rounds and five false
 * ones shipped anyway, because the sweep was HTML that cmark wrote - the
 * vocabulary this tool's own pipeline emits - and the input that produces a
 * false note is HTML somebody else wrote. `spec/pasted-html.corpus.json` is
 * that input: hand-written documents, the markup a dozen products are known
 * to emit, and what Chromium's and Firefox's own serialisers put on the
 * clipboard. `spec/pasted-html.oracle.json` is what Chromium, Firefox and
 * WebKit drew for each - generated by scripts/generate-pasted-html-oracle.mjs,
 * which does not read the census, and committed. Nothing here renders; the
 * rendering is in the fixture, from real engines, because jsdom has none.
 *
 * WHAT IS HELD, and against what:
 *
 *   - An ELEMENT note ("could not carry", "invented") on a document whose
 *     round trip no engine draws differently is false. None may fire.
 *   - Every element such a note names on a document that DID change must be
 *     one whose presence at least one engine can see.
 *   - The positive half: a round trip an engine draws differently is never
 *     silent, and an element every engine can see going or arriving is named -
 *     so the rules that stop the false notes cannot pass by stopping all of
 *     them.
 *   - The sanitiser's element note names only elements the allow-list really
 *     refuses, because that is what its sentence says.
 *
 * WHAT IS NOT, and why: attribute, class and identifier notes. A lost `class`
 * renders as nothing and is still a loss to whoever had a stylesheet for it,
 * so pixels cannot judge it. Those notes keep their own tests.
 */

const context: ToolRunContext = { signal: new AbortController().signal };

const ENGINES = ['chromium', 'firefox', 'webkit'] as const;
type Engine = (typeof ENGINES)[number];

interface Comparison {
  readonly visible: boolean;
  readonly sameAccessibilityTree: boolean;
}

interface Unwrapped extends Record<Engine, Comparison> {
  readonly direction: 'fewer' | 'more';
}

interface OracleEntry {
  readonly id: string;
  readonly sanitised: string;
  readonly normalised: string;
  readonly sanitiser: Record<Engine, Comparison>;
  readonly roundTrip: Record<Engine, Comparison>;
  readonly unwrapped: Readonly<Record<string, Unwrapped>>;
}

interface Calibration {
  readonly engine: Engine;
  readonly pair: readonly [string, string];
  readonly expected: 'seen' | 'unseen';
  readonly byInk: boolean;
  readonly byLayout: boolean;
}

interface CorpusDocument {
  readonly id: string;
  readonly kind: 'hand-written' | 'export-shape' | 'clipboard';
  readonly html: string;
}

const corpus = corpusFile as unknown as { readonly documents: readonly CorpusDocument[] };
const oracle = oracleFile as unknown as {
  readonly calibration: readonly Calibration[];
  readonly entries: readonly OracleEntry[];
};

const TARGETS = ['html', 'markdown'] as const;

/** Read off the schema itself, not off the set the tool is handed. */
const ALLOWED_ELEMENTS: ReadonlySet<string> = new Set(SANITISE_SCHEMA.tagNames ?? []);

interface Note {
  readonly level: string;
  readonly title: string;
  readonly body: string;
}

async function run(html: string, target: string): Promise<{ output: string; notes: Note[] }> {
  const result = await textConvertTool.run({
    inputs: { input: { type: 'text', text: html } },
    options: { source: 'html', target },
    context,
  });
  if (!result.ok) throw new Error(`${result.error.code}: ${result.error.message}`);
  const report = result.value.report;
  if (report?.type !== 'json' || !isJsonObject(report.data)) throw new Error('no report');
  const raw = report.data.notes;
  const output = result.value.output;
  return {
    output: output?.type === 'text' ? output.text : '',
    notes:
      raw !== undefined && isJsonArray(raw)
        ? raw.filter(isJsonObject).map((note) => ({
            level: typeof note.level === 'string' ? note.level : '',
            title: typeof note.title === 'string' ? note.title : '',
            body: typeof note.body === 'string' ? note.body : '',
          }))
        : [],
  };
}

/** The `<tag>` names in the part of a body before `marker`. */
function tagsBefore(body: string, marker: RegExp): string[] {
  const head = body.split(marker)[0] ?? '';
  return [...head.matchAll(/<([a-z][a-z0-9:-]*)>/g)].map((match) => match[1] ?? '');
}

/** What the round trip's element notes say, as tag names. */
function elementClaims(notes: readonly Note[]): {
  readonly dropped: string[];
  readonly added: string[];
  readonly paragraph: boolean;
} {
  const dropped: string[] = [];
  const added: string[] = [];
  for (const note of notes) {
    if (note.level !== 'warn') continue;
    if (/elements? the round trip could not carry/.test(note.title)) {
      dropped.push(...tagsBefore(note.body.replace(/^Markdown has no spelling for /, ''), /, so /));
    }
    if (note.title.includes('invented by the round trip')) {
      added.push(...tagsBefore(note.body, / (is|are) in the result/));
    }
  }
  return {
    dropped,
    added,
    paragraph: notes.some((note) => note.title === 'Loose content was put in a paragraph'),
  };
}

const entryFor = (id: string): OracleEntry => {
  const entry = oracle.entries.find((candidate) => candidate.id === id);
  if (!entry) throw new Error(`${id} is in the corpus and not the oracle: regenerate it`);
  return entry;
};

const seenBy = (comparisons: Record<Engine, Comparison>): Engine[] =>
  ENGINES.filter((engine) => comparisons[engine].visible);

const cases = corpus.documents.flatMap((document) =>
  TARGETS.map((target) => [document.id, target, document] as const),
);

describe('the oracle', () => {
  it('covers every corpus document, and nothing else', () => {
    expect(oracle.entries.map((entry) => entry.id)).toEqual(
      corpus.documents.map((document) => document.id),
    );
  });

  it.each(corpus.documents.map((document) => [document.id, document] as const))(
    'is about the documents the tool still produces for %s',
    async (_id, document) => {
      // A changed pipeline makes the verdicts below about documents nobody
      // produces any more. Regenerate: node scripts/generate-pasted-html-oracle.mjs
      const entry = entryFor(document.id);
      expect((await run(document.html, 'html-sanitised')).output).toBe(entry.sanitised);
      expect((await run(document.html, 'html')).output).toBe(entry.normalised);
    },
  );

  /*
   * The oracle's own positive and negative partner, asserted on the fixture
   * rather than trusted from the generator's log: a hand-edited verdict that
   * made a seen pair unseen would otherwise pass everything below.
   */
  it('saw every calibration change it had to see, in every engine', () => {
    const seen = oracle.calibration.filter((entry) => entry.expected === 'seen');
    expect(seen.length).toBeGreaterThanOrEqual(12 * ENGINES.length);
    expect(seen.filter((entry) => !entry.byInk && !entry.byLayout)).toEqual([]);
  });

  it('saw none of the calibration non-changes, in any engine', () => {
    const unseen = oracle.calibration.filter((entry) => entry.expected === 'unseen');
    expect(unseen.length).toBeGreaterThanOrEqual(3 * ENGINES.length);
    expect(unseen.filter((entry) => entry.byInk || entry.byLayout)).toEqual([]);
  });

  it('has documents on both sides of the question', () => {
    // A corpus in which nothing is visible, or everything is, would let the
    // tests below pass on a census that always or never speaks.
    const visible = oracle.entries.filter((entry) => seenBy(entry.roundTrip).length > 0);
    expect(visible.length).toBeGreaterThan(15);
    expect(oracle.entries.length - visible.length).toBeGreaterThan(15);
  });
});

describe('no element note where no engine draws a difference', () => {
  it.each(cases)('%s, to %s', async (_id, target, document) => {
    const entry = entryFor(document.id);
    if (seenBy(entry.roundTrip).length > 0) return;
    const { dropped, added } = elementClaims((await run(document.html, target)).notes);
    expect({ dropped, added }).toEqual({ dropped: [], added: [] });
  });
});

describe('every element a note names is one an engine can see', () => {
  /*
   * Asked per element, by unwrapping every element of that name in the
   * document that has more of them: if no engine draws the document any
   * differently without them, then their going or arriving is not something a
   * reader can see.
   *
   * TWO NAMES ARE CARRIED WITH A REASON RATHER THAN HELD, and the reason is a
   * limit of that question, not of the note. Unwrapping every `<tr>` in a
   * table lets CSS build an anonymous row for the cells, so a `<tr>` the round
   * trip added is invisible to the unwrap even when the row it holds is the
   * empty header row the note is about - which the `<th>` beside it in the
   * same note is seen for. And a `<div>` that carries an attribute is counted
   * on purpose (`rendering.ts`, rule 2): what it loses is the attribute, which
   * pixels cannot see.
   */
  const CARRIED: Readonly<Record<string, string>> = {
    tr: 'CSS makes an anonymous row when every <tr> is unwrapped; the <th> is held instead',
  };

  it.each(cases)('%s, to %s', async (_id, target, document) => {
    const entry = entryFor(document.id);
    const { dropped, added } = elementClaims((await run(document.html, target)).notes);
    const unseen = [...dropped, ...added].filter((tag) => {
      if (CARRIED[tag] !== undefined) return false;
      const unwrapped = entry.unwrapped[tag];
      if (unwrapped === undefined) return true;
      if (seenBy(unwrapped).length > 0) return false;
      // An element with attributes is counted for the attribute's sake.
      return !new RegExp(`<${tag}\\s`).test(entry.sanitised + entry.normalised);
    });
    expect(unseen).toEqual([]);
  });
});

describe('a change every engine can see is never silent', () => {
  it.each(cases)('%s, to %s', async (_id, target, document) => {
    const entry = entryFor(document.id);
    if (seenBy(entry.roundTrip).length < ENGINES.length) return;
    const { notes } = await run(document.html, target);
    const roundTrip = notes.filter((note) =>
      /round trip|paragraph/.test(`${note.title} ${note.body}`),
    );
    expect(roundTrip.map((note) => note.title)).not.toEqual([]);
  });

  it.each(cases)(
    'names every element every engine sees go or arrive in %s, to %s',
    async (_id, target, document) => {
      const entry = entryFor(document.id);
      if (seenBy(entry.roundTrip).length === 0) return;
      const { dropped, added, paragraph } = elementClaims((await run(document.html, target)).notes);
      const said = new Set([...dropped, ...added, ...(paragraph ? ['p'] : [])]);

      /*
       * Unwrapping every element of one name asks whether that name's presence
       * shows, not whether the round trip lost what it drew - and where other
       * names ARRIVE in the same document, what one drew may now be drawn by
       * another. Two such shapes are left out, each for a reason the doc-level
       * question above still holds to account:
       *
       *   one rendering under two names - `<b>` gone and `<strong>` come;
       *   a block that drew nothing and the paragraphs that replaced it - two
       *   `<div>` lines become two `<p>`, and unwrapping the divs merges the
       *   lines, but the paragraphs keep them apart and are what is said.
       */
      const CARRIED_BY_WHAT_ARRIVED: Readonly<Record<string, string>> = {
        b: 'one rendering with <strong>',
        strong: 'one rendering with <b>',
        i: 'one rendering with <em>',
        em: 'one rendering with <i>',
        s: 'one rendering with <del>',
        strike: 'one rendering with <del>',
        del: 'one rendering with <s>',
        tt: 'one rendering with <code>',
        code: 'one rendering with <tt>',
        div: 'draws nothing; the lines it kept apart are kept apart by the <p> that arrived',
      };
      const moved = Object.entries(entry.unwrapped).filter(
        ([, unwrapped]) => seenBy(unwrapped).length === ENGINES.length,
      );
      const somethingArrived = moved.some(([, unwrapped]) => unwrapped.direction === 'more');
      const required = moved
        .filter(([tag]) => !somethingArrived || CARRIED_BY_WHAT_ARRIVED[tag] === undefined)
        .map(([tag]) => tag);
      expect(required.filter((tag) => !said.has(tag))).toEqual([]);
    },
  );
});

describe('the sanitiser names only what its list refuses', () => {
  it.each(cases)('%s, to %s', async (_id, target, document) => {
    const { notes } = await run(document.html, target);
    const refused = notes
      .filter((note) => /elements? (was|were) removed by the sanitiser/.test(note.title))
      .flatMap((note) => tagsBefore(note.body, / (is|are) not on the allowed list/));
    expect(refused.filter((tag) => ALLOWED_ELEMENTS.has(tag))).toEqual([]);
  });

  it('says a link whose address was refused became its words', async () => {
    const { output, notes } = await run(
      '<p><a href="javascript:alert(1)">click me</a> or <a href="https://example.com">this one</a></p>',
      'html-sanitised',
    );
    expect(output).toContain('click me');
    expect(output).not.toContain('javascript');
    const note = notes.find((entry) => entry.title === '1 link became plain text');
    // eslint-disable-next-line no-script-url -- the scheme the note names, not a URL
    expect(note?.body).toContain('javascript:');
    expect(notes.some((entry) => entry.title.includes('removed by the sanitiser'))).toBe(false);
  });

  it('says an image whose source was refused became its alt text', async () => {
    const { output, notes } = await run(
      '<p><img src="javascript:void(0)" alt="the logo"> beside text</p>',
      'html-sanitised',
    );
    expect(output).toContain('the logo');
    expect(notes.map((entry) => entry.title)).toEqual(['1 image was replaced by its alt text']);
  });

  it.each([
    ['a link that keeps its address', '<p><a href="https://example.com">safe</a></p>'],
    ['a relative link', '<p><a href="/docs">docs</a></p>'],
    ['an anchor that was never a link', '<p><a name="top">top</a></p>'],
    ['an image with a source it keeps', '<p><img src="https://example.com/a.png" alt="a"></p>'],
  ])('says nothing about links or images for %s', async (_label, html) => {
    const { notes } = await run(html, 'html-sanitised');
    expect(notes.filter((note) => /link became|links became|alt text/.test(note.title))).toEqual(
      [],
    );
  });

  it('still names an element the list does refuse, beside one it keeps', async () => {
    // The positive partner: filtering by the list must not empty the note.
    const { notes } = await run(
      '<article><p><a href="javascript:x">go</a></p><center>mid</center></article>',
      'html-sanitised',
    );
    const note = notes.find((entry) => entry.title.includes('removed by the sanitiser'));
    expect(note?.body).toContain('<article>');
    expect(note?.body).toContain('<center>');
    expect(note?.body).not.toContain('<a>');
  });
});

/*
 * THE THREE NOTES ROUND SIXTEEN ADDED, held across the whole corpus to a count
 * the census does not take. Each is an element count, which is a thing jsdom's
 * parser represents exactly, so it is counted here with the DOM rather than
 * with the census the notes are built on.
 */
const count = (html: string, selector: string): number =>
  new DOMParser().parseFromString(`<body>${html}</body>`, 'text/html').querySelectorAll(selector)
    .length;

describe('the new notes fire exactly where their subject is', () => {
  it.each(cases)('the paragraph note, %s to %s', async (_id, target, document) => {
    const entry = entryFor(document.id);
    const { notes } = await run(document.html, target);
    const said = notes.filter((note) => note.title === 'Loose content was put in a paragraph');
    const gained = count(entry.normalised, 'p') > count(entry.sanitised, 'p');
    expect(said.length).toBe(gained ? 1 : 0);
    expect(said.every((note) => note.level === 'info')).toBe(true);
  });

  it.each(cases)('the link and image notes, %s to %s', async (_id, target, document) => {
    const entry = entryFor(document.id);
    const { notes } = await run(document.html, target);
    const links = count(document.html, 'a[href]') - count(entry.sanitised, 'a[href]');
    const images = count(document.html, 'img[src]') - count(entry.sanitised, 'img[src]');
    const titles = notes.map((note) => note.title);
    expect(titles.filter((title) => /links? became plain text/.test(title))).toEqual(
      links > 0 ? [`${String(links)} ${links === 1 ? 'link' : 'links'} became plain text`] : [],
    );
    expect(titles.filter((title) => /replaced by (its|their) alt text/.test(title)).length).toBe(
      images > 0 ? 1 : 0,
    );
  });

  it('has a document on each side of each of them', () => {
    // So the two loops above are not satisfied by a corpus that never has
    // the subject at all.
    const gains = oracle.entries.filter(
      (entry) => count(entry.normalised, 'p') > count(entry.sanitised, 'p'),
    );
    expect(gains.length).toBeGreaterThan(5);
    expect(oracle.entries.length - gains.length).toBeGreaterThan(5);
    const refusedLinks = corpus.documents.filter(
      (document) =>
        count(document.html, 'a[href]') > count(entryFor(document.id).sanitised, 'a[href]'),
    );
    expect(refusedLinks.map((document) => document.id)).toContain('refused-link');
    expect(
      corpus.documents.filter((document) => count(document.html, 'a[href]') > 0).length,
    ).toBeGreaterThan(5);
  });
});

describe('an invented paragraph is said, and not as a loss', () => {
  it('says so for text that was in a div', async () => {
    const { output, notes } = await run('<div>just a line of text</div>', 'html');
    expect(output).toBe('<p>just a line of text</p>');
    expect(notes.map((note) => [note.level, note.title])).toEqual([
      ['info', 'Loose content was put in a paragraph'],
    ]);
  });

  it('says it on the Markdown target, naming the document it was measured on', async () => {
    const { notes } = await run('<h1>Title</h1>Text after the heading.', 'markdown');
    const note = notes.find((entry) => entry.title === 'Loose content was put in a paragraph');
    expect(note?.body).toContain('Measured by rendering this Markdown back to HTML');
  });

  it.each([
    ['a paragraph already', '<p>already one</p>'],
    ['a quotation already holding one', '<blockquote><p>quoted</p></blockquote>'],
    ['a list item', '<ul><li>one</li></ul>'],
  ])('says nothing about %s', async (_label, html) => {
    const { notes } = await run(html, 'html');
    expect(notes.filter((note) => note.title.includes('paragraph'))).toEqual([]);
  });
});
