/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsToolIdRouteImport } from './routes/tools/$toolId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/styleguide.lazy').then((d) => d.Route))
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/tools/index.lazy').then((d) => d.Route))
const ToolsToolIdRoute = ToolsToolIdRouteImport.update({
  id: '/tools/$toolId',
  path: '/tools/$toolId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/tools/$toolId.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/styleguide': typeof StyleguideRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/styleguide': typeof StyleguideRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/styleguide': typeof StyleguideRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/styleguide' | '/tools/$toolId' | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/styleguide' | '/tools/$toolId' | '/tools'
  id: '__root__' | '/' | '/styleguide' | '/tools/$toolId' | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StyleguideRoute: typeof StyleguideRoute
  ToolsToolIdRoute: typeof ToolsToolIdRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolId': {
      id: '/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof ToolsToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StyleguideRoute: StyleguideRoute,
  ToolsToolIdRoute: ToolsToolIdRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
